name: Docs Build

on:
  push:
    paths:
    - 'docs/**'
    - '.github/**/*docs*'
  pull_request:
    paths:
    - 'docs/**'
    - '.github/**/*docs*'

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

jobs:
  GitHub_Pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1.1.2
      with:
        ruby-version: 2.6.x
    - name: Build
      run: |
        ./.github/scripts/docs.sh
